# Generated by Django 5.1.3 on 2024-11-25 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('free-field', 'Free Field'), ('ongoing', 'Ongoing'), ('under-review', 'Under Review'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('returned', 'Returned')], default='free-field', max_length=20),
        ),
    ]
