# Generated by Django 5.1.3 on 2024-11-25 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_kanbanpreference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KanbanPreference',
        ),
    ]
