# Generated by Django 5.1.3 on 2024-11-25 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_todos', to='todo.todo'),
        ),
    ]
